// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Formplug","status":true,"description":"Allows users to give a thumbs up, down or Wiggle to Formbar and interact with Formbar API via socket.io-client.","parameters":{"Formbar URL":"https://formbeta.yorktechapps.com/","API Key":"7045571e79b752752c84a2b67f42f0eaa5f1093501b3935c6aeab28f6ee17084a441ca79d96e482acaf84992f04fb7778bc211234e0d866ce798bb8e91c4afba"}}
];
